// Generated by CoffeeScript 1.7.1
(function() {
  (function($) {
    var ajaxCallDribble, baseSettings;
    ajaxCallDribble = function(url, options, pagination) {
      var data;
      data = {};
      if (pagination) {
        data.page = options.page;
        data.per_page = options.per_page;
      }
      return $.ajax({
        url: "http://api.dribbble.com" + url,
        dataType: "jsonp",
        data: data
      }).done(options.callback);
    };
    baseSettings = {
      callback: function() {},
      per_page: 15,
      page: 1,
      id: ""
    };
    $.dribbble = {
      getShot: function(opts) {
        var options;
        options = $.extend({}, baseSettings, opts);
        ajaxCallDribble("/shots/" + options.id, options, false);
      },
      getShots: function(opts) {
        var options;
        options = $.extend({}, baseSettings, opts);
        ajaxCallDribble("/shots/everyone/", options, true);
      },
      getPlayerShots: function(opts) {
        var options;
        options = $.extend({}, baseSettings, opts);
        ajaxCallDribble("/players/" + options.id + "/shots", options, true);
      },
      getPlayerShotsFollowing: function(opts) {
        var options;
        options = $.extend({}, baseSettings, opts);
        ajaxCallDribble("/players/" + options.id + "/shots/following", options, true);
      }
    };
  })(jQuery);

  (function($) {
    var ajaxCallYouTube, baseSettings;
    ajaxCallYouTube = function(url, options) {
      var data;
      data = {};
      return $.ajax({
        url: "http://gdata.youtube.com" + url,
        dataType: "jsonp",
        data: data
      }).done(options.callback);
    };
    baseSettings = {
      callback: function() {},
      q: "",
      maxResults: 1,
      alt: "jsonc"
    };
    $.youtube = {
      getVideoPlaylist: function(opts) {
        var options;
        options = $.extend({}, baseSettings, opts);
        ajaxCallYouTube("/feeds/api/videos?q=" + options.q + "&max_result=" + options.maxResults + "&v=2&alt=" + options.alt, options, false);
      },
      getUserDetails: function(opts) {
        var options;
        options = $.extend({}, baseSettings, opts);
        ajaxCallYouTube("/feeds/api/users/" + options.q + "/playlists?v=2&alt=" + options.alt, options, false);
      }
    };
  })(jQuery);

  $.dribbble.getShot({
    id: "0001",
    callback: function(data) {
      console.log("get the specific data");
      console.log(data);
    }
  });

  $.dribbble.getShots({
    callback: function(data) {
      console.log("get all  data");
      console.log(data);
    }
  });

  $.youtube.getVideoPlaylist({
    q: "aNdMiIAlK0g",
    callback: function(data) {
      console.log("get the youtube playlist data");
      console.log(data);
    }
  });

  $.youtube.getUserDetails({
    q: "GY27OwqTX-J9VZDVNS_I2g",
    callback: function(data) {
      console.log("get the youtube USER DETAILS");
      console.log(data);
    }
  });

}).call(this);

//# sourceMappingURL=chp010.map
