// Generated by CoffeeScript 1.6.3
(function() {
  var car, consoleMe, doubleListNumber, listNumber, newArrayMagic, num, number, opposite, result, two, _i, _j, _len, _len1;

  number = 42;

  opposite = true;

  number = -42;

  if (opposite) {
    console.log(number);
  }

  two = 2;

  result = two + two;

  console.log("2+2 is : " + result);

  listNumber = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  console.log(listNumber);

  doubleListNumber = [];

  /*+++Loop definition with condition in coffeescript+++*/


  for (_i = 0, _len = listNumber.length; _i < _len; _i++) {
    num = listNumber[_i];
    if (num % 2 === 0) {
      doubleListNumber.push(Math.pow(num, 2));
    }
  }

  console.log(doubleListNumber);

  newArrayMagic = [];

  for (_j = 0, _len1 = listNumber.length; _j < _len1; _j++) {
    num = listNumber[_j];
    newArrayMagic.push(num);
  }

  console.log(newArrayMagic);

  car = {
    'wheelCount': 4,
    'color': 'red',
    'seatCount': 5,
    'carMaximumSpeed': 99
  };

  console.log("the color of this car is : " + car.color);

  console.log("the number of seats is : " + car.seatCount);

  console.log("the wheels number are : " + car.wheelCount);

  console.log("car maximum speed: " + car.carMaximumSpeed);

  consoleMe = function(expression) {
    return console.log(expression);
  };

  consoleMe('this is for running basic function');

}).call(this);

/*
//@ sourceMappingURL=chp001.map
*/
