// Generated by CoffeeScript 1.6.3
(function() {
  var bodyElement, indexCounter, redBox, redBoxCounterContainer, toggleBox;

  bodyElement = $('body');

  $(bodyElement).css('background-color', 'rgb(252, 252, 252)');

  redBox = $('#box001');

  redBoxCounterContainer = $('span#counter');

  indexCounter = 0;

  toggleBox = function(indexCounter) {
    'undefined';
    return $(redBox).fadeToggle('slow', function() {
      indexCounter++;
      if (indexCounter < 10) {
        redBoxCounterContainer.text(indexCounter);
        toggleBox(indexCounter);
        return "undefined";
      }
    });
  };

  toggleBox(indexCounter);

}).call(this);

/*
//@ sourceMappingURL=chp002.map
*/
