// Generated by CoffeeScript 1.6.3
(function() {
  var allNavList, allPragraph, familyContainer, fastestChild, mainTable;

  allPragraph = $("p");

  console.log(allPragraph.length);

  allPragraph.addClass("pregraphCore");

  fastestChild = $("p strong").text();

  console.log("did you find the child ? " + fastestChild);

  console.log("did you find the child ? " + allPragraph.first().children('strong').text());

  console.log("did you find the child ? " + allPragraph.first().find('strong').text());

  allNavList = $(".nav li");

  console.log("the first list item in nav is : " + allNavList.first().text());

  console.log("the second list item in nav is : " + allNavList.eq(1).text());

  console.log("the last list item in nav is : " + allNavList.last().text());

  familyContainer = $("#family");

  console.log($("#family span").siblings().append('--->').text());

  console.log($("#brother005").prevAll().text());

  console.log($("#brother005").nextAll().text());

  console.log($("#brother005").prevAll().andSelf().text());

  console.log($("#brother005").nextAll().andSelf().text());

  console.log("who is my parent?" + $("#brother005").parent().attr("id"));

  mainTable = $("#mainTable");

  $('td:even').css("background-color", "yellow");

  $('td:odd').css("background-color", "red");

  $("div.filterDiv").css("background", "#c8ebcc").filter(".middle").css("border-color", "red");

}).call(this);

/*
//@ sourceMappingURL=chp003.map
*/
