// Generated by CoffeeScript 1.7.1
(function() {
  $.fn.logId = function() {
    this.each(function() {
      if (this.id !== "") {
        console.log(this.id);
      }
    });
    $.fn.logAttr = function(attr) {
      return this.each(function() {
        if ($(this).attr(attr) !== void 0) {
          console.log($(this).attr(attr));
        }
      });
    };
  };

  $(function() {
    $("div").logId();
  });

  $(function() {
    $("div").logAttr("class");
  });

  (function($) {
    $.fn.logAttrBook = function(opts) {
      var defaults, options;
      defaults = {
        attr: "id",
        backup: "N/A",
        useAlert: true
      };
      options = $.extend({}, defaults, opts);
      return this.each(function() {
        var val;
        val = $(this).attr(options.attr) || options.backup;
        if (options.useAlert) {
          alert(val);
        } else {
          console.log(val);
        }
      });
    };
  })(jQuery);

  $(function() {});

  $("div").logAttrBook({
    attr: "id",
    useAlert: false,
    backup: "Not Aviliable"
  });

  (function($) {
    $.fn.accordion = function(opts) {
      var defaults, options;
      defaults = {
        headings: "h2",
        content: "p",
        callback: function() {
          return console.log("end of animate");
        },
        duration: 600
      };
      options = $.extend({}, defaults, opts);
      return this.each(function() {
        var $this, animateAccordion, headings, paragraphs;
        $this = $(this);
        headings = $this.children(options.headings);
        paragraphs = $this.children(options.content);
        animateAccordion = function(elem, duration, callback) {
          paragraphs.stop(true, true).slideUp(duration);
          $(elem).stop(true, true).slideDown(duration, callback);
        };
        paragraphs.not(":first").hide();
        $this.on("click", options.headings, function() {
          var t, tPara;
          t = $(this);
          tPara = t.next();
          if (!tPara.is(":visible")) {
            tPara.trigger("showParagraph");
          }
        });
        $this.on("showParagraph", options.content, function() {
          animateAccordion(this, options.duration, options.callback);
        });
      });
    };
  })(jQuery);

  $(function() {
    return $("#accordion").accordion({
      duration: 1000,
      callback: console.log("override"),
      headings: "h2",
      content: "p"
    });
  });

}).call(this);

//# sourceMappingURL=main.map
