// Generated by CoffeeScript 1.6.3
(function() {
    var headerNavSelector, i;

    headerNavSelector = $('.nav');

    i = 1;

    headerNavSelector.on('click', 'li', function () {
        console.log('header element is clicked for the ' + i + ' time');
        return i++;
    });

    headerNavSelector.append('<li><a>portfilo</a></li>');

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
